name: BuildLab

on:
  push:
    paths:
      - '*.txt"

jobs:
  node-docker:
    runs-on: self-hosted
    
    env:
      IMAGE_NAME: build-lab-container
  
    container: 
      image: registry.access.redhat.com/ubi8/ubi:latest
