name: ci

on: [push]
#on:
#  push:
#    branches:
#      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    
    container:
      image: centos:7
    
    steps:
      -
        name: build
        run: |
          echo "----- Start Build -----"
          echo "----- End Build -----"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rinn9999/app:latest

